/* SET V13.4.1 — persistent global product shell */
(function(){
 const DB=window.CastDB,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
 const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const toast=m=>{let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.append(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
 const role=()=>DB.currentUser()?.role||'guest';
 const route={home:()=>role()==='guest'?'index.html':'dashboard.html',discover:(cat='all')=>'discover.html'+(cat&&cat!=='all'?('?category='+encodeURIComponent(cat)):''),talent:id=>'talent.html?id='+encodeURIComponent(id),photographer:id=>'photographer.html?id='+encodeURIComponent(id),company:id=>'company.html?id='+encodeURIComponent(id),casting:id=>'casting.html?id='+encodeURIComponent(id),project:(id,tab='overview')=>'project-workspace.html?project='+encodeURIComponent(id)+'&tab='+encodeURIComponent(tab)};
 const homeHref=route.home;
 function ensureSiteHeader(){
  if(document.body.dataset.page==='auth')return;
  let h=document.querySelector('.site-header');
  if(!h){
   h=document.createElement('header');h.className='site-header v13-persistent-header';
   h.innerHTML=`<div class="container nav-wrap"><a class="brand" href="index.html" aria-label="SET الرئيسية"><img class="set-wordmark" src="set-wordmark.svg" alt="SET"><img class="set-brand-mark compact-only" src="set-mark.svg" alt="SET"></a><nav class="main-nav" aria-label="التنقل الرئيسي"><a href="feed.html" data-top-nav="home">الرئيسية</a><a href="discover.html" data-top-nav="discover">اكتشف</a><a href="castings.html" data-top-nav="castings">فرص الكاستنغ</a><a href="reels.html" data-top-nav="reels">Reels</a></nav><div class="nav-actions" id="navActions"></div></div>`;
   document.body.prepend(h);
  }else h.classList.add('v13-persistent-header');
  const p=document.body.dataset.page||'';
  const key=p==='feed'?'home':p.includes('discover')||p==='explore'?'discover':p==='castings'||p==='casting'?'castings':p==='reels'?'reels':'';
  h.querySelectorAll('[data-top-nav],.main-nav a').forEach(a=>{const href=a.getAttribute('href')||'';const is=(key==='home'&&href.includes('feed.html'))||(key==='discover'&&(href.includes('discover.html')||href.includes('explore.html')))||(key==='castings'&&href.includes('castings.html'))||(key==='reels'&&href.includes('reels.html'));a.classList.toggle('active',!!is)});
  if(!DB.currentUser()){
   const z=h.querySelector('#navActions');if(z&&!z.children.length)z.innerHTML='<button class="v13-theme-toggle" type="button" data-set-theme-toggle aria-label="تبديل المظهر"></button><a class="btn secondary sm" href="auth.html#login">تسجيل الدخول</a>';
  }
 }
 const icon=(name)=>({home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5v8a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>',discover:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="m16 16 4 4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',create:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',inbox:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v11H8l-4 4z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>',profile:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M5 20c.8-4 3.1-6 7-6s6.2 2 7 6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',chevron:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 10 4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>',settings:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M19 13.5v-3l-2-.7a7 7 0 0 0-.8-1.8l.9-1.9-2.2-2.1-1.9.9a7 7 0 0 0-1.8-.8L10.5 2h-3l-.7 2.1a7 7 0 0 0-1.8.8L3.1 4 1 6.1 1.9 8a7 7 0 0 0-.8 1.8L-1 10.5v3l2.1.7a7 7 0 0 0 .8 1.8L1 17.9 3.1 20l1.9-.9a7 7 0 0 0 1.8.8l.7 2.1h3l.7-2.1a7 7 0 0 0 1.8-.8l1.9.9 2.2-2.1-.9-1.9a7 7 0 0 0 .8-1.8z" fill="none" stroke="currentColor" stroke-width="1.3" transform="translate(3 0)"/></svg>'})[name]||'';
 function roleCreate(){return({photographer:[['New Project','dashboard.html#projects'],['Upload Work','feed.html']],director:[['New Project','dashboard.html#projects'],['New Board','project-workspace.html']],company:[['New Casting','dashboard.html#projects'],['New Project','dashboard.html#projects']],talent:[['Post Work','feed.html'],['Update availability','settings.html']],admin:[['Platform Control','dashboard.html#features']]})[role()]||[['Create account','auth.html#signup']]}
 function accountHeader(){
  const u=DB.currentUser();if(!u)return;
  const roleNames={talent:'حساب موهبة',photographer:'حساب مصور',company:'حساب شركة',director:'حساب مخرج',admin:'حساب إدارة'};
  const initial=esc((u.name||'U').trim().charAt(0)||'U');
  const profileHref=u.role==='talent'?'dashboard.html#profile':u.role==='photographer'?'dashboard.html#profile':u.role==='company'?'company.html':'settings.html';
  const roleLinks=u.role==='talent'?`<a role="menuitem" href="dashboard.html#profile">${icon('profile')}<span>تعديل البروفايل</span></a><a role="menuitem" href="discover.html?category=opportunities"><span class="v13-menu-dot">◉</span><span>الفرص</span></a><a role="menuitem" href="dashboard.html#applications"><span class="v13-menu-dot">✓</span><span>طلباتي</span></a><a role="menuitem" href="dashboard.html#invitations"><span class="v13-menu-dot">+</span><span>الدعوات</span></a>`:u.role==='photographer'?`<a role="menuitem" href="dashboard.html#profile">${icon('profile')}<span>تعديل البروفايل</span></a><a role="menuitem" href="dashboard.html#projects"><span class="v13-menu-dot">▣</span><span>مشاريعي</span></a><a role="menuitem" href="discover.html?category=talents"><span class="v13-menu-dot">⌕</span><span>المواهب المحفوظة والاكتشاف</span></a>`:u.role==='company'?`<a role="menuitem" href="${profileHref}">${icon('profile')}<span>حساب الشركة</span></a><a role="menuitem" href="dashboard.html#submissions"><span class="v13-menu-dot">✓</span><span>المتقدمون</span></a><a role="menuitem" href="dashboard.html#projects"><span class="v13-menu-dot">▣</span><span>الكاستنغ والمشاريع</span></a>`:`<a role="menuitem" href="${profileHref}">${icon('profile')}<span>حسابي</span></a>`;
  const menu=`<div class="v13-account-wrap"><button class="v13-account-trigger" type="button" aria-haspopup="menu" aria-expanded="false"><span class="v13-account-avatar">${initial}</span><span class="v13-account-copy"><b>${esc(u.name||'الحساب')}</b><small>${roleNames[u.role]||'حساب'}</small></span><span class="v13-account-chevron">${icon('chevron')}</span></button><div class="v13-account-menu" role="menu" hidden>${roleLinks}<div class="v13-account-menu-sep"></div><a role="menuitem" href="settings.html">${icon('settings')}<span>الإعدادات والخصوصية</span></a><button role="menuitem" type="button" data-v13-account-logout><span class="v13-logout-icon">↪</span><span>تسجيل الخروج</span></button></div></div>`;
  const topNav=$('#navActions');
  if(topNav){topNav.classList.add('v13-top-account-zone');topNav.innerHTML=`<button class="v13-theme-toggle" type="button" data-set-theme-toggle aria-label="تبديل المظهر"></button><a class="v13-top-icon" href="inbox.html" aria-label="الرسائل">${icon('inbox')}</a>${menu}`}
  const dash=$('.dash-top-actions');
  if(dash&&!document.querySelector('.v13-persistent-header')){const notif=$('#notificationBtn');dash.querySelector('a[href="settings.html"]')?.remove();dash.insertAdjacentHTML('beforeend',menu);if(notif){notif.classList.add('v13-top-icon');notif.innerHTML=`<span class="v13-bell">◌</span><span id="notifCount">${esc($('#notifCount')?.textContent||'')}</span>`}}
  $$('.v13-account-wrap').forEach(w=>{const btn=w.querySelector('.v13-account-trigger'),m=w.querySelector('.v13-account-menu');const close=()=>{m.hidden=true;btn.setAttribute('aria-expanded','false');w.classList.remove('open')};btn.addEventListener('click',e=>{e.stopPropagation();const open=m.hidden;m.hidden=!open;btn.setAttribute('aria-expanded',String(open));w.classList.toggle('open',open)});w.querySelector('[data-v13-account-logout]')?.addEventListener('click',()=>{DB.logout();location.href='index.html'});document.addEventListener('click',e=>{if(!w.contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})});
 }
 function shell(){
  $$('.v13-global-nav,.v13-create-sheet').forEach(x=>x.remove());
  if(document.body.classList.contains('pw-body'))return;
  const nav=document.createElement('nav');nav.className='v13-global-nav';nav.setAttribute('aria-label','التنقل الرئيسي');
  const items=[['home',homeHref(),'الرئيسية'],['discover','discover.html','اكتشف'],['create','#','إنشاء'],['inbox','inbox.html','الرسائل'],['profile',role()==='guest'?'auth.html':'settings.html','الحساب']];
  nav.innerHTML=items.map(([k,h,l])=>`<a href="${h}" data-v13-nav="${k}" aria-label="${l}"><span>${icon(k)}</span><small>${l}</small></a>`).join('');document.body.append(nav);
  const page=document.body.dataset.page||'';const active=page.includes('discover')?'discover':page==='inbox-v13'?'inbox':page==='dashboard'?'home':page==='settings'||page.includes('talent')||page.includes('company')||page.includes('photographer')?'profile':'';
  if(active)$(`[data-v13-nav="${active}"]`)?.classList.add('active');
  $('[data-v13-nav="create"]')?.addEventListener('click',e=>{e.preventDefault();openCreate()});
 }
 function openCreate(){document.querySelector('.v13-create-sheet')?.remove();let s=document.createElement('div');s.className='v13-create-sheet';s.innerHTML=`<button class="v13-sheet-backdrop" aria-label="إغلاق"></button><section role="dialog" aria-modal="true" aria-label="إنشاء"><div class="v13-sheet-head"><b>إنشاء</b><button data-v13-close aria-label="إغلاق">×</button></div>${roleCreate().map(([l,h])=>`<a href="${h}">${esc(l)}<span>←</span></a>`).join('')}</section>`;document.body.append(s);document.body.classList.add('overlay-open');const close=()=>{s.remove();document.body.classList.remove('overlay-open')};requestAnimationFrame(()=>s.classList.add('open'));s.onclick=e=>{if(e.target.matches('[data-v13-close],.v13-sheet-backdrop'))close()};s._closeOverlay=close}
 function verified(){return `<span class="v13-verified" aria-label="موثق"><svg viewBox="0 0 24 24"><path d="M23 12l-2.4-2.8.3-3.7-3.6-.8-1.9-3.2L12 3 8.6 1.5 6.7 4.7l-3.6.8.3 3.7L1 12l2.4 2.8-.3 3.7 3.6.8 1.9 3.2L12 21l3.4 1.5 1.9-3.2 3.6-.8-.3-3.7L23 12z"/><path class="check" d="m7.2 12.1 2.1 2.2 7-7 1.4 1.4-8.4 8.4-3.5-3.6z"/></svg></span>`}
 function talentCard(t){const u=DB.currentUser(),canAdd=['photographer','company','director'].includes(u?.role);return `<article class="v13-person-card"><a class="v13-person-media" href="talent.html?id=${t.id}"><img loading="lazy" src="${t.image||'image-placeholder.svg'}" alt="${esc(t.name)}"></a><div class="v13-person-copy"><div><b>${esc(t.name)}${t.verified?verified():''}</b><small>${esc(t.type)} · ${esc(t.city)}</small></div><div class="v13-tags">${(t.skills||[]).slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="v13-card-actions"><button data-save-talent="${t.id}" class="v13-icon-action" aria-label="حفظ">${DB.isSaved?.('talent',t.id)?'★':'☆'}</button>${canAdd?`<button data-add-talent="${t.id}" class="btn primary sm">Add to Project</button>`:''}<a class="btn ghost sm" href="talent.html?id=${t.id}">View</a></div></div></article>`}
 function photographerCard(p){return `<article class="v13-person-card"><a class="v13-person-media" href="photographer.html?id=${p.id}"><img loading="lazy" src="${p.image||'image-placeholder.svg'}" alt="${esc(p.name)}"></a><div class="v13-person-copy"><div><b>${esc(p.name)}${p.verified?verified():''}</b><small>Photographer · ${esc(p.city)}</small></div><div class="v13-tags">${(p.specialties||[]).slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="v13-card-actions"><button data-save-photo="${p.id}" class="v13-icon-action" aria-label="حفظ المصور">${DB.isSaved?.('photographer',p.id)?'★':'☆'}</button>${['company','director'].includes(role())?`<button data-invite-photo="${p.id}" class="btn primary sm">Invite</button>`:''}<a class="btn ghost sm" href="photographer.html?id=${p.id}">View Work</a></div></div></article>`}
 function companyCard(c){return `<article class="v13-company-card"><div class="v13-company-logo">${esc((c.name||'C')[0])}</div><div><b>${esc(c.name)}${c.verified?verified():''}</b><small>${esc(c.type)} · ${esc(c.city)}</small><p>${esc(c.bio||'')}</p><div class="v13-card-actions"><button data-save-company="${c.id}" class="v13-icon-action" aria-label="حفظ الشركة">${DB.isSaved?.('company',c.id)?'★':'☆'}</button><a class="btn primary sm" href="company.html?id=${c.id}">View opportunities</a></div></div></article>`}
 function castingCard(p){const s=DB.state(),c=s.companies.find(x=>x.id===p.companyId);return `<article class="v13-opportunity-card"><div><small>${esc(p.category)} · ${esc(p.city)}</small><h3>${esc(p.title)}</h3><p>${esc(c?.name||'')} · Shoot ${esc(p.shootDate)}</p></div><div><b>${esc(p.budget)}</b><a class="btn primary sm" href="casting.html?id=${p.id}">View / Apply</a></div></article>`}
 function discover(){if(document.body.dataset.page!=='discover-v13')return;const s=DB.ensureV13(),q=$('#v13Search'),tabs=$$('[data-v13-category]');let cat=(new URLSearchParams(location.search).get('category')||'all'); tabs.forEach(b=>b.classList.toggle('active',b.dataset.v13Category===cat));
  function render(){const text=(q.value||'').trim().toLowerCase(),hit=(x)=>JSON.stringify(x).toLowerCase().includes(text);let html='';
   if(cat==='all'||cat==='talents'){const list=s.talents.filter(hit);if(list.length)html+=`<section><div class="v13-section-head"><h2>Talents</h2><span>${list.length}</span></div><div class="v13-discover-grid">${list.map(talentCard).join('')}</div></section>`}
   if(cat==='all'||cat==='photographers'){const list=(s.photographers||[]).filter(hit);if(list.length)html+=`<section><div class="v13-section-head"><h2>Photographers</h2><span>${list.length}</span></div><div class="v13-discover-grid">${list.map(photographerCard).join('')}</div></section>`}
   if(cat==='all'||cat==='companies'){const list=s.companies.filter(hit);if(list.length)html+=`<section><div class="v13-section-head"><h2>Companies</h2><span>${list.length}</span></div><div class="v13-company-grid">${list.map(companyCard).join('')}</div></section>`}
   if(cat==='all'||cat==='opportunities'){const list=s.castings.filter(x=>x.status==='open'&&hit(x));if(list.length)html+=`<section><div class="v13-section-head"><h2>Opportunities</h2><span>${list.length}</span></div><div class="v13-opportunity-list">${list.map(castingCard).join('')}</div></section>`}
   $('#v13Results').innerHTML=html||`<div class="v13-empty"><h2>ماكو نتائج</h2><p>جرّب اسم، مدينة، تخصص أو نوع فرصة مختلف.</p><button class="btn primary" data-v13-clear-search>مسح البحث والفلاتر</button></div>`;wireDiscover(); $('[data-v13-clear-search]')?.addEventListener('click',()=>{q.value='';cat='all';tabs.forEach(x=>x.classList.toggle('active',x.dataset.v13Category==='all'));history.replaceState(null,'','discover.html');render()})}
  function wireDiscover(){$$('[data-save-talent]').forEach(b=>b.onclick=()=>{DB.toggleSaved('talent',b.dataset.saveTalent);render()});$$('[data-save-photo]').forEach(b=>b.onclick=()=>{DB.toggleSaved('photographer',b.dataset.savePhoto);render()});$$('[data-save-company]').forEach(b=>b.onclick=()=>{DB.toggleSaved('company',b.dataset.saveCompany);render()});$$('[data-add-talent]').forEach(b=>b.onclick=()=>quickAddTalent(b.dataset.addTalent));$$('[data-invite-photo]').forEach(b=>b.onclick=()=>{DB.createInvite('photographer',b.dataset.invitePhoto);toast('تم إرسال الدعوة')})}
  function quickAddTalent(id){const st=DB.state(),u=DB.currentUser();if(!u)return location.href='auth.html#login';if(u.role==='photographer'){const ph=DB.currentPhotographer?.();const projects=(st.photoProjects||[]).filter(p=>p.photographerId===ph?.id);if(!projects.length)return location.href='dashboard.html#projects';const p=projects[0];DB.addTalentToPhotoProject(p.id,id);toast('تمت الإضافة إلى '+p.name)}else if(u.role==='company'){const c=st.companies.find(x=>x.userId===u.id);let sl=st.shortlists.find(x=>x.companyId===c?.id);if(!sl)sl=DB.createShortlist(c.id,st.castings.find(x=>x.companyId===c?.id)?.id||'','Quick Shortlist');DB.addShortlistItem(sl.id,id);toast('تمت الإضافة إلى Shortlist')}else{DB.toggleSaved('talent',id);toast('تم حفظ الموهبة للقائمة')}}
  q.oninput=render;tabs.forEach(b=>b.onclick=()=>{cat=b.dataset.v13Category;tabs.forEach(x=>x.classList.toggle('active',x===b));render()});render()}
 function dashboard(){if(document.body.dataset.page!=='dashboard')return;const u=DB.currentUser();if(!u||u.role==='admin')return;const host=$('#dashboardContent');if(!host)return;const d=DB.roleHomeData(),s=DB.state();$('#dashboardTitle')&&($('#dashboardTitle').textContent='الرئيسية');
  const head=`<section class="v13-home-hero"><div><small>${new Date().toLocaleDateString('ar-IQ',{weekday:'long',day:'numeric',month:'long'})}</small><h1>هلا، ${esc((u.name||'').split(' ')[0])}</h1><p>${({talent:'الفرص والتحديثات المهمة إلك.',photographer:'مشاريعك والتصوير الجاي.',company:'الكاستنغ والطلبات اللي تحتاج قرار.',director:'المشاريع والتخطيط والاختيارات.'})[u.role]||''}</p></div><button class="btn primary" data-v13-create-home>+ إنشاء</button></section>`;
  let content='';
  if(u.role==='photographer'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Active Projects</h2><button class="v13-text-action" data-v13-dash-go="projects">كل المشاريع</button></div><div class="v13-project-row">${(d.projects||[]).slice(0,4).map(p=>`<a href="project-workspace.html?project=${p.id}" class="v13-project-card"><b>${esc(p.name)}</b><small>${p.shootDate?'Shoot '+p.shootDate:'Continue planning'}</small><span>فتح المشروع ←</span></a>`).join('')||'<button class="v13-empty-card" data-v13-dash-go="projects">أنشئ أول مشروع</button>'}</div></section><section class="v13-action-block"><div class="v13-section-head"><h2>Saved Talents</h2><a href="discover.html?category=talents">اكتشف</a></div><div class="v13-mini-people">${(d.saved||[]).slice(0,5).map(t=>`<a href="talent.html?id=${t.id}"><img src="${t.image||'image-placeholder.svg'}"><span>${esc(t.name)}</span></a>`).join('')||'<p>احفظ المواهب حتى ترجع إلهم بسرعة.</p>'}</div></section>`}
  if(u.role==='talent'){content=`<section class="v13-talent-quick"><a href="dashboard.html#profile"><b>تعديل البروفايل</b><small>حدّث صورك ومعلوماتك</small></a><a href="dashboard.html#applications"><b>طلباتي</b><small>تابع حالة تقديماتك</small></a><a href="dashboard.html#invitations"><b>الدعوات</b><small>طلبات المشاريع والتعاون</small></a><a href="settings.html"><b>الإعدادات</b><small>الخصوصية والإشعارات</small></a></section><section class="v13-action-block"><div class="v13-section-head"><h2>Opportunities for you</h2><a href="discover.html?category=opportunities">كل الفرص</a></div><div class="v13-opportunity-list">${(d.castings||[]).map(castingCard).join('')}</div></section><section class="v13-action-block"><div class="v13-section-head"><h2>Application updates</h2><span>${(d.applications||[]).length}</span></div>${(d.applications||[]).map(a=>{const p=s.castings.find(x=>x.id===a.projectId);return `<a class="v13-update-row" href="casting.html?id=${a.projectId}"><b>${esc(p?.title||'Casting')}</b><span>${esc(a.status)}</span></a>`}).join('')||'<div class="v13-empty-inline">بعد ما عندك تحديثات.</div>'}</section>`}
  if(u.role==='company'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Applications needing review</h2><button class="v13-text-action" data-v13-dash-go="submissions">عرض الكل</button></div>${(d.applications||[]).slice(0,6).map(a=>{const t=s.talents.find(x=>x.id===a.talentId);return `<div class="v13-review-row"><img src="${t?.image||'image-placeholder.svg'}"><div><b>${esc(t?.name||'Talent')}</b><small>${esc(t?.city||'')}</small></div><button class="btn primary sm" data-v13-review="${a.id}">Review</button></div>`}).join('')||'<div class="v13-empty-inline">ماكو طلبات تنتظر مراجعة.</div>'}</section><section class="v13-action-block"><div class="v13-section-head"><h2>Active Castings</h2><button class="v13-text-action" data-v13-dash-go="projects">إدارة الكاستنغ</button></div><div class="v13-opportunity-list">${(d.castings||[]).map(castingCard).join('')}</div></section>`}
  if(u.role==='director'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Director Workspace</h2><a href="discover.html">اكتشف الفريق</a></div><div class="v13-empty-inline">مشاريع المخرج المشتركة تحتاج دعوة Project collaborator. ما نعرض روابط Projects غير مصرّح بها.</div></section>`}
  host.innerHTML=`<div class="v13-home-shell">${head}${content}<section class="v13-action-block"><div class="v13-section-head"><h2>Needs your attention</h2><a href="inbox.html">Inbox</a></div><div class="v13-notification-list">${(d.notifications||[]).slice(0,5).map(n=>`<div><b>${esc(n.title)}</b><small>${esc(n.body)}</small></div>`).join('')||'<div class="v13-empty-inline">كلشي مرتب حالياً.</div>'}</div></section></div>`;
  $('[data-v13-create-home]')?.addEventListener('click',openCreate);
  $$('[data-v13-dash-go]').forEach(b=>b.onclick=()=>{$(`#dashboardNav [data-dash="${b.dataset.v13DashGo}"]`)?.click()});
  $$('[data-v13-review]').forEach(b=>b.onclick=()=>{if(typeof window.showApplicationManager==='function')window.showApplicationManager(b.dataset.v13Review);else $(`#dashboardNav [data-dash="submissions"]`)?.click()});
  $$('#dashboardNav [data-dash]').forEach(a=>{if(a.dataset.v13HomeBound)return;a.dataset.v13HomeBound='1';a.addEventListener('click',()=>{if(a.dataset.dash==='overview')setTimeout(dashboard,0)})});
 }
 function openThread(c,other){const old=document.querySelector('.v13-thread-sheet');old?.remove();const box=document.createElement('div');box.className='v13-thread-sheet';box.innerHTML=`<button class="v13-sheet-backdrop" aria-label="إغلاق المحادثة"></button><section role="dialog" aria-modal="true" aria-label="محادثة ${esc(other?.name||'')}"><div class="v13-sheet-head"><div><b>${esc(other?.name||'محادثة')}</b><small>${esc(c.contextTitle||'')}</small></div><button data-v13-thread-close aria-label="إغلاق">×</button></div><div class="v13-thread-messages">${(c.messages||[]).map(m=>`<div class="${m.senderId===DB.currentUser()?.id?'mine':''}"><p>${esc(m.text)}</p><small>${new Date(m.at).toLocaleString('ar-IQ')}</small></div>`).join('')}</div></section>`;document.body.append(box);document.body.classList.add('overlay-open');const close=()=>{box.remove();document.body.classList.remove('overlay-open')};box._closeOverlay=close;requestAnimationFrame(()=>box.classList.add('open'));box.addEventListener('click',e=>{if(e.target.closest('[data-v13-thread-close]')||e.target.classList.contains('v13-sheet-backdrop'))close()})}
 function inbox(){if(document.body.dataset.page!=='inbox-v13')return;const u=DB.currentUser();if(!u)return location.href='auth.html#login';const conv=DB.conversationsForUser(),s=DB.state();$('#v13Inbox').innerHTML=conv.length?conv.map(c=>{const last=(c.messages||[]).at(-1);const other=(c.members||[]).map(id=>s.users.find(x=>x.id===id)).find(x=>x&&x.id!==u.id);return `<button class="v13-thread" data-v13-thread="${c.id}"><div class="v13-thread-avatar">${esc((other?.name||'C')[0])}</div><div><b>${esc(other?.name||'Conversation')}</b><small>${esc(c.contextTitle)}</small><p>${esc(last?.text||'')}</p></div><span>›</span></button>`}).join(''):`<div class="v13-empty"><h2>ماكو رسائل بعد</h2><p>الرسائل المرتبطة بمشروع أو Casting راح تظهر هنا.</p><a class="btn primary" href="discover.html">اكتشف أشخاص</a></div>`;$$('[data-v13-thread]').forEach(b=>b.onclick=()=>{const c=conv.find(x=>x.id===b.dataset.v13Thread),other=(c?.members||[]).map(id=>s.users.find(x=>x.id===id)).find(x=>x&&x.id!==u.id);if(c)openThread(c,other)})}
 function authDirector(){if(document.body.dataset.page!=='auth')return;const wrap=$('.account-choice');if(wrap&&!wrap.querySelector('[data-role="director"]')){const b=document.createElement('button');b.className='account-choice-card';b.dataset.role='director';b.innerHTML='<span>🎥</span><div><b>مخرج</b><small>Director · Visual planning</small></div>';wrap.append(b);b.onclick=()=>{const hidden=$('#signupRole');if(hidden)hidden.value='director';$$('[data-role]').forEach(x=>x.classList.toggle('active',x===b));const ex=$('#signupExtra');if(ex)ex.innerHTML='<option>Commercial Director</option><option>Film Director</option><option>Content Director</option>'}}
  const demos=$('.demo-logins');if(demos&&!demos.querySelector('[data-demo="director@castiraq.demo"]')){const b=document.createElement('button');b.dataset.demo='director@castiraq.demo';b.innerHTML='Director<small>123456</small>';b.onclick=()=>{$('#loginEmail').value=b.dataset.demo;$('#loginPassword').value='123456'};demos.append(b)}}
 function profileActions(){if(document.body.dataset.page!=='talent')return;setTimeout(()=>{const u=DB.currentUser(),host=$('#profileHeader'),side=$('#profileActions');if(!u||!host)return;const id=new URLSearchParams(location.search).get('id')||'t1';if(['photographer','company','director'].includes(u.role)){const acts=`<div class="v13-profile-actions"><button class="btn primary" data-v13-add-profile>Add to Project</button><button class="btn secondary" data-v13-message>Message</button><button class="v13-icon-action" data-v13-save-profile>${DB.isSaved?.('talent',id)?'★':'☆'}</button></div>`;host.querySelector('.profile-header-actions')?.replaceChildren();host.querySelector('.profile-header-actions')?.insertAdjacentHTML('beforeend',acts);if(side)side.hidden=true;$('[data-v13-save-profile]')?.addEventListener('click',()=>{DB.toggleSaved('talent',id);toast('تم الحفظ')});$('[data-v13-add-profile]')?.addEventListener('click',()=>{if(u.role==='photographer'){const p=(DB.state().photoProjects||[]).find(x=>x.photographerId===DB.currentPhotographer?.()?.id);if(p){DB.addTalentToPhotoProject(p.id,id);toast('تمت الإضافة إلى '+p.name)}else location.href='dashboard.html#projects'}else{DB.toggleSaved('talent',id);toast('تمت الإضافة للقائمة')}});$('[data-v13-message]')?.addEventListener('click',()=>location.href='inbox.html')}} ,80)}

 document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const thread=document.querySelector('.v13-thread-sheet');if(thread){e.preventDefault();thread._closeOverlay?.();return}const s=document.querySelector('.v13-create-sheet');if(s){e.preventDefault();s._closeOverlay?.();return}const m=document.querySelector('#appModal.show');if(m&&typeof window.closeModal==='function'){e.preventDefault();window.closeModal()}});
 document.addEventListener('DOMContentLoaded',()=>{DB.ensureV13?.();ensureSiteHeader();shell();accountHeader();discover();dashboard();inbox();authDirector();profileActions()});
})();
