/* Cast Iraq V13 — unified multi-role UX */
(function(){
 const DB=window.CastDB,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
 const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const toast=m=>{let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.append(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
 const role=()=>DB.currentUser()?.role||'guest';
 const homeHref=()=>role()==='guest'?'index.html':'dashboard.html';
 function roleCreate(){return({photographer:[['New Project','dashboard.html#projects'],['Upload Work','feed.html']],director:[['New Project','dashboard.html#projects'],['New Board','project-workspace.html']],company:[['New Casting','dashboard.html#casting'],['New Project','dashboard.html#projects']],talent:[['Post Work','feed.html'],['Update availability','settings.html']],admin:[['Platform Control','dashboard.html#features']]})[role()]||[['Create account','auth.html#signup']]}
 function shell(){
  $$('.v13-global-nav,.v13-create-sheet').forEach(x=>x.remove());
  const nav=document.createElement('nav');nav.className='v13-global-nav';nav.setAttribute('aria-label','التنقل الرئيسي');
  const items=[['home',homeHref(),'الرئيسية','⌂'],['discover','discover.html','اكتشف','⌕'],['create','#','إنشاء','＋'],['inbox','inbox.html','الرسائل','◌'],['profile',role()==='guest'?'auth.html':'settings.html','الحساب','○']];
  nav.innerHTML=items.map(([k,h,l,i])=>`<a href="${h}" data-v13-nav="${k}" aria-label="${l}"><span>${i}</span><small>${l}</small></a>`).join('');document.body.append(nav);
  const page=document.body.dataset.page||'';const active=page.includes('discover')?'discover':page==='inbox-v13'?'inbox':page==='dashboard'?'home':page==='settings'||page.includes('talent')||page.includes('company')||page.includes('photographer')?'profile':'';
  if(active)$(`[data-v13-nav="${active}"]`)?.classList.add('active');
  $('[data-v13-nav="create"]')?.addEventListener('click',e=>{e.preventDefault();openCreate()});
 }
 function openCreate(){let s=document.createElement('div');s.className='v13-create-sheet';s.innerHTML=`<button class="v13-sheet-backdrop" aria-label="إغلاق"></button><section><div class="v13-sheet-head"><b>إنشاء</b><button data-v13-close>×</button></div>${roleCreate().map(([l,h])=>`<a href="${h}">${esc(l)}<span>←</span></a>`).join('')}</section>`;document.body.append(s);requestAnimationFrame(()=>s.classList.add('open'));s.onclick=e=>{if(e.target.matches('[data-v13-close],.v13-sheet-backdrop'))s.remove()}}
 function verified(){return `<span class="v13-verified" aria-label="موثق"><svg viewBox="0 0 24 24"><path d="M23 12l-2.4-2.8.3-3.7-3.6-.8-1.9-3.2L12 3 8.6 1.5 6.7 4.7l-3.6.8.3 3.7L1 12l2.4 2.8-.3 3.7 3.6.8 1.9 3.2L12 21l3.4 1.5 1.9-3.2 3.6-.8-.3-3.7L23 12z"/><path class="check" d="m7.2 12.1 2.1 2.2 7-7 1.4 1.4-8.4 8.4-3.5-3.6z"/></svg></span>`}
 function talentCard(t){const u=DB.currentUser(),canAdd=['photographer','company','director'].includes(u?.role);return `<article class="v13-person-card"><a class="v13-person-media" href="talent.html?id=${t.id}"><img loading="lazy" src="${t.image||'image-placeholder.svg'}" alt="${esc(t.name)}"></a><div class="v13-person-copy"><div><b>${esc(t.name)}${t.verified?verified():''}</b><small>${esc(t.type)} · ${esc(t.city)}</small></div><div class="v13-tags">${(t.skills||[]).slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="v13-card-actions"><button data-save-talent="${t.id}" class="v13-icon-action" aria-label="حفظ">${DB.isSaved?.('talent',t.id)?'★':'☆'}</button>${canAdd?`<button data-add-talent="${t.id}" class="btn primary sm">Add to Project</button>`:''}<a class="btn ghost sm" href="talent.html?id=${t.id}">View</a></div></div></article>`}
 function photographerCard(p){return `<article class="v13-person-card"><a class="v13-person-media" href="photographer.html?id=${p.id}"><img loading="lazy" src="${p.image||'image-placeholder.svg'}" alt="${esc(p.name)}"></a><div class="v13-person-copy"><div><b>${esc(p.name)}${p.verified?verified():''}</b><small>Photographer · ${esc(p.city)}</small></div><div class="v13-tags">${(p.specialties||[]).slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="v13-card-actions"><button data-save-photo="${p.id}" class="v13-icon-action">${DB.isSaved?.('photographer',p.id)?'★':'☆'}</button>${['company','director'].includes(role())?`<button data-invite-photo="${p.id}" class="btn primary sm">Invite</button>`:''}<a class="btn ghost sm" href="photographer.html?id=${p.id}">View Work</a></div></div></article>`}
 function companyCard(c){return `<article class="v13-company-card"><div class="v13-company-logo">${esc((c.name||'C')[0])}</div><div><b>${esc(c.name)}${c.verified?verified():''}</b><small>${esc(c.type)} · ${esc(c.city)}</small><p>${esc(c.bio||'')}</p><div class="v13-card-actions"><button data-save-company="${c.id}" class="v13-icon-action">${DB.isSaved?.('company',c.id)?'★':'☆'}</button><a class="btn primary sm" href="company.html?id=${c.id}">View opportunities</a></div></div></article>`}
 function castingCard(p){const s=DB.state(),c=s.companies.find(x=>x.id===p.companyId);return `<article class="v13-opportunity-card"><div><small>${esc(p.category)} · ${esc(p.city)}</small><h3>${esc(p.title)}</h3><p>${esc(c?.name||'')} · Shoot ${esc(p.shootDate)}</p></div><div><b>${esc(p.budget)}</b><a class="btn primary sm" href="casting.html?id=${p.id}">View / Apply</a></div></article>`}
 function discover(){if(document.body.dataset.page!=='discover-v13')return;const s=DB.ensureV13(),q=$('#v13Search'),tabs=$$('[data-v13-category]');let cat=(new URLSearchParams(location.search).get('category')||'all'); tabs.forEach(b=>b.classList.toggle('active',b.dataset.v13Category===cat));
  function render(){const text=(q.value||'').trim().toLowerCase(),hit=(x)=>JSON.stringify(x).toLowerCase().includes(text);let html='';
   if(cat==='all'||cat==='talents'){const list=s.talents.filter(hit);if(list.length)html+=`<section><div class="v13-section-head"><h2>Talents</h2><span>${list.length}</span></div><div class="v13-discover-grid">${list.map(talentCard).join('')}</div></section>`}
   if(cat==='all'||cat==='photographers'){const list=(s.photographers||[]).filter(hit);if(list.length)html+=`<section><div class="v13-section-head"><h2>Photographers</h2><span>${list.length}</span></div><div class="v13-discover-grid">${list.map(photographerCard).join('')}</div></section>`}
   if(cat==='all'||cat==='companies'){const list=s.companies.filter(hit);if(list.length)html+=`<section><div class="v13-section-head"><h2>Companies</h2><span>${list.length}</span></div><div class="v13-company-grid">${list.map(companyCard).join('')}</div></section>`}
   if(cat==='all'||cat==='opportunities'){const list=s.castings.filter(x=>x.status==='open'&&hit(x));if(list.length)html+=`<section><div class="v13-section-head"><h2>Opportunities</h2><span>${list.length}</span></div><div class="v13-opportunity-list">${list.map(castingCard).join('')}</div></section>`}
   $('#v13Results').innerHTML=html||`<div class="v13-empty"><h2>ماكو نتائج</h2><p>جرّب اسم، مدينة، تخصص أو نوع فرصة مختلف.</p></div>`;wireDiscover()}
  function wireDiscover(){$$('[data-save-talent]').forEach(b=>b.onclick=()=>{DB.toggleSaved('talent',b.dataset.saveTalent);render()});$$('[data-save-photo]').forEach(b=>b.onclick=()=>{DB.toggleSaved('photographer',b.dataset.savePhoto);render()});$$('[data-save-company]').forEach(b=>b.onclick=()=>{DB.toggleSaved('company',b.dataset.saveCompany);render()});$$('[data-add-talent]').forEach(b=>b.onclick=()=>quickAddTalent(b.dataset.addTalent));$$('[data-invite-photo]').forEach(b=>b.onclick=()=>{DB.createInvite('photographer',b.dataset.invitePhoto);toast('تم إرسال الدعوة')})}
  function quickAddTalent(id){const st=DB.state(),u=DB.currentUser();if(!u)return location.href='auth.html#login';if(u.role==='photographer'){const ph=DB.currentPhotographer?.();const projects=(st.photoProjects||[]).filter(p=>p.photographerId===ph?.id);if(!projects.length)return location.href='dashboard.html#projects';const p=projects[0];DB.addTalentToPhotoProject(p.id,id);toast('تمت الإضافة إلى '+p.name)}else{DB.toggleSaved('talent',id);toast('تم حفظ الموهبة للقائمة')}}
  q.oninput=render;tabs.forEach(b=>b.onclick=()=>{cat=b.dataset.v13Category;tabs.forEach(x=>x.classList.toggle('active',x===b));render()});render()}
 function dashboard(){if(document.body.dataset.page!=='dashboard')return;const u=DB.currentUser();if(!u||u.role==='admin')return;const main=$('main');if(!main)return;const d=DB.roleHomeData();
  const head=`<section class="v13-home-hero"><div><small>${new Date().toLocaleDateString('ar-IQ',{weekday:'long',day:'numeric',month:'long'})}</small><h1>هلا، ${esc((u.name||'').split(' ')[0])}</h1><p>${({talent:'الفرص والتحديثات المهمة إلك.',photographer:'مشاريعك والتصوير الجاي.',company:'الكاستنغ والطلبات اللي تحتاج قرار.',director:'المشاريع والتخطيط والاختيارات.'})[u.role]||''}</p></div><button class="btn primary" data-v13-create-home>+ إنشاء</button></section>`;
  let content='';const s=DB.state();
  if(u.role==='photographer'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Active Projects</h2><a href="#projects">كل المشاريع</a></div><div class="v13-project-row">${(d.projects||[]).slice(0,4).map(p=>`<a href="project-workspace.html?project=${p.id}" class="v13-project-card"><b>${esc(p.name)}</b><small>${p.shootDate?'Shoot '+p.shootDate:'Continue planning'}</small><span>فتح المشروع ←</span></a>`).join('')||'<a class="v13-empty-card" href="#projects">أنشئ أول مشروع</a>'}</div></section><section class="v13-action-block"><div class="v13-section-head"><h2>Saved Talents</h2><a href="discover.html?category=talents">اكتشف</a></div><div class="v13-mini-people">${(d.saved||[]).slice(0,5).map(t=>`<a href="talent.html?id=${t.id}"><img src="${t.image}"><span>${esc(t.name)}</span></a>`).join('')||'<p>احفظ المواهب حتى ترجع إلهم بسرعة.</p>'}</div></section>`}
  if(u.role==='talent'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Opportunities for you</h2><a href="discover.html?category=opportunities">كل الفرص</a></div><div class="v13-opportunity-list">${(d.castings||[]).map(castingCard).join('')}</div></section><section class="v13-action-block"><div class="v13-section-head"><h2>Application updates</h2><span>${(d.applications||[]).length}</span></div>${(d.applications||[]).map(a=>{const p=s.castings.find(x=>x.id===a.projectId);return `<a class="v13-update-row" href="casting.html?id=${a.projectId}"><b>${esc(p?.title||'Casting')}</b><span>${esc(a.status)}</span></a>`}).join('')||'<div class="v13-empty-inline">بعد ما عندك تحديثات.</div>'}</section>`}
  if(u.role==='company'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Applications needing review</h2><span>${(d.applications||[]).length}</span></div>${(d.applications||[]).slice(0,6).map(a=>{const t=s.talents.find(x=>x.id===a.talentId);return `<div class="v13-review-row"><img src="${t?.image||'image-placeholder.svg'}"><div><b>${esc(t?.name||'Talent')}</b><small>${esc(t?.city||'')}</small></div><button class="btn primary sm">Review</button></div>`}).join('')||'<div class="v13-empty-inline">ماكو طلبات تنتظر مراجعة.</div>'}</section><section class="v13-action-block"><div class="v13-section-head"><h2>Active Castings</h2><a href="castings.html">كل الكاستنغ</a></div><div class="v13-opportunity-list">${(d.castings||[]).map(castingCard).join('')}</div></section>`}
  if(u.role==='director'){content=`<section class="v13-action-block"><div class="v13-section-head"><h2>Active Projects</h2><a href="discover.html">اكتشف الفريق</a></div><div class="v13-project-row">${(d.projects||[]).map(p=>`<a class="v13-project-card" href="project-workspace.html?project=${p.id}"><b>${esc(p.name)}</b><small>Boards · Shots · Planning</small><span>Open ←</span></a>`).join('')||'<div class="v13-empty-card">ماكو مشاريع مشتركة حالياً.</div>'}</div></section>`}
  main.innerHTML=`<div class="v13-home-shell">${head}${content}<section class="v13-action-block"><div class="v13-section-head"><h2>Needs your attention</h2><a href="inbox.html">Inbox</a></div><div class="v13-notification-list">${(d.notifications||[]).slice(0,5).map(n=>`<div><b>${esc(n.title)}</b><small>${esc(n.body)}</small></div>`).join('')||'<div class="v13-empty-inline">كلشي مرتب حالياً.</div>'}</div></section></div>`;$('[data-v13-create-home]')?.addEventListener('click',openCreate)}
 function inbox(){if(document.body.dataset.page!=='inbox-v13')return;const u=DB.currentUser();if(!u)return location.href='auth.html#login';const conv=DB.conversationsForUser(),s=DB.state();$('#v13Inbox').innerHTML=conv.length?conv.map(c=>{const last=(c.messages||[]).at(-1);const other=(c.members||[]).map(id=>s.users.find(x=>x.id===id)).find(x=>x&&x.id!==u.id);return `<article class="v13-thread"><div class="v13-thread-avatar">${esc((other?.name||'C')[0])}</div><div><b>${esc(other?.name||'Conversation')}</b><small>${esc(c.contextTitle)}</small><p>${esc(last?.text||'')}</p></div><span>›</span></article>`}).join(''):`<div class="v13-empty"><h2>ماكو رسائل بعد</h2><p>الرسائل المرتبطة بمشروع أو Casting راح تظهر هنا.</p><a class="btn primary" href="discover.html">اكتشف أشخاص</a></div>`}
 function authDirector(){if(document.body.dataset.page!=='auth')return;const wrap=$('.account-choice');if(wrap&&!wrap.querySelector('[data-role="director"]')){const b=document.createElement('button');b.className='account-choice-card';b.dataset.role='director';b.innerHTML='<span>🎥</span><div><b>مخرج</b><small>Director · Visual planning</small></div>';wrap.append(b);b.onclick=()=>{const hidden=$('#signupRole');if(hidden)hidden.value='director';$$('[data-role]').forEach(x=>x.classList.toggle('active',x===b));const ex=$('#signupExtra');if(ex)ex.innerHTML='<option>Commercial Director</option><option>Film Director</option><option>Content Director</option>'}}
  const demos=$('.demo-logins');if(demos&&!demos.querySelector('[data-demo="director@castiraq.demo"]')){const b=document.createElement('button');b.dataset.demo='director@castiraq.demo';b.innerHTML='Director<small>123456</small>';b.onclick=()=>{$('#loginEmail').value=b.dataset.demo;$('#loginPassword').value='123456'};demos.append(b)}}
 function profileActions(){if(document.body.dataset.page!=='talent')return;setTimeout(()=>{const u=DB.currentUser(),host=$('#profileHeader'),side=$('#profileActions');if(!u||!host)return;const id=new URLSearchParams(location.search).get('id')||'t1';if(['photographer','company','director'].includes(u.role)){const acts=`<div class="v13-profile-actions"><button class="btn primary" data-v13-add-profile>Add to Project</button><button class="btn secondary" data-v13-message>Message</button><button class="v13-icon-action" data-v13-save-profile>${DB.isSaved?.('talent',id)?'★':'☆'}</button></div>`;host.querySelector('.profile-header-actions')?.replaceChildren();host.querySelector('.profile-header-actions')?.insertAdjacentHTML('beforeend',acts);if(side)side.hidden=true;$('[data-v13-save-profile]')?.addEventListener('click',()=>{DB.toggleSaved('talent',id);toast('تم الحفظ')});$('[data-v13-add-profile]')?.addEventListener('click',()=>{if(u.role==='photographer'){const p=(DB.state().photoProjects||[]).find(x=>x.photographerId===DB.currentPhotographer?.()?.id);if(p){DB.addTalentToPhotoProject(p.id,id);toast('تمت الإضافة إلى '+p.name)}else location.href='dashboard.html#projects'}else{DB.toggleSaved('talent',id);toast('تمت الإضافة للقائمة')}});$('[data-v13-message]')?.addEventListener('click',()=>location.href='inbox.html')}} ,80)}
 document.addEventListener('DOMContentLoaded',()=>{DB.ensureV13?.();shell();discover();dashboard();inbox();authDirector();profileActions()});
})();
