/* Cast Iraq V12 — Photographer Reality data layer */
(function(){
  const DB=window.CastDB;if(!DB)return;
  const now=()=>new Date().toISOString();
  const uid=p=>p+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
  const arr=(s,k)=>{if(!Array.isArray(s[k]))s[k]=[];return s[k]};
  function ensureV12(){
    const s=DB.ensureV10?DB.ensureV10():DB.state();let changed=false;
    ['projectLocations','projectLooks','projectProps','lightingSetups','cameraSetups','shotGroups'].forEach(k=>{if(!Array.isArray(s[k])){s[k]=[];changed=true}});
    (s.photoProjects||[]).forEach(p=>{
      const defs={callTime:'',status:'planning',client:'',lastContext:null};
      Object.entries(defs).forEach(([k,v])=>{if(!(k in p)){p[k]=v;changed=true}});
    });
    (s.scenes||[]).forEach((sc,i)=>{
      const defs={sceneNumber:i+1,locationId:'',lookId:'',lightingSetupId:'',cameraSetupId:'',referenceAssetId:'',timeOfDay:'',generalLook:'',talentIds:[],estimatedMinutes:0,notes:''};
      Object.entries(defs).forEach(([k,v])=>{if(!(k in sc)){sc[k]=Array.isArray(v)?[]:v;changed=true}});
    });
    (s.shots||[]).forEach((sh,i)=>{
      const defs={planningStatus:'draft',captureStatus:sh.captureStatus||'not_shot',storyOrder:sh.position||i+1,shootingOrder:sh.position||i+1,priority:'must',estimatedMinutes:5,locationId:'',lookId:'',lightingSetupId:'',cameraSetupId:'',propIds:[],referenceAssetIds:sh.assetId?[sh.assetId]:[],groupId:'',quickNote:'',skipReason:''};
      Object.entries(defs).forEach(([k,v])=>{if(!(k in sh)){sh[k]=Array.isArray(v)?[...v]:v;changed=true}});
    });
    if(changed)DB.save(s);return s;
  }
  function ownProject(projectId){const s=ensureV12(),ph=DB.currentPhotographer?.(),p=s.photoProjects.find(x=>x.id===projectId&&x.photographerId===ph?.id);if(!p)throw new Error('PROJECT_NOT_FOUND');return[s,p,ph]}
  function addProjectEntity(projectId,kind,data={}){const [s]=ownProject(projectId);const map={location:'projectLocations',look:'projectLooks',prop:'projectProps',lighting:'lightingSetups',camera:'cameraSetups'};const key=map[kind];if(!key)throw new Error('ENTITY_KIND_INVALID');const item={id:uid(kind),projectId,name:String(data.name||'').trim()||({location:'Location',look:'Look',prop:'Prop',lighting:'Lighting Setup',camera:'Camera Setup'})[kind],image:data.image||'',notes:data.notes||'',createdAt:now(),...data};s[key].push(item);DB.save(s);return item}
  function updateProjectEntity(kind,id,patch){const s=ensureV12(),map={location:'projectLocations',look:'projectLooks',prop:'projectProps',lighting:'lightingSetups',camera:'cameraSetups'},item=s[map[kind]]?.find(x=>x.id===id);if(!item)throw new Error('ENTITY_NOT_FOUND');Object.assign(item,patch,{updatedAt:now()});DB.save(s);return item}
  function entitiesFor(projectId,kind){const s=ensureV12(),map={location:'projectLocations',look:'projectLooks',prop:'projectProps',lighting:'lightingSetups',camera:'cameraSetups'};return (s[map[kind]]||[]).filter(x=>x.projectId===projectId)}
  function updateSceneV12(id,patch){const s=ensureV12(),sc=s.scenes.find(x=>x.id===id);if(!sc)throw new Error('SCENE_NOT_FOUND');Object.assign(sc,patch,{updatedAt:now()});DB.save(s);return sc}
  function effectiveShot(shot){const s=ensureV12(),sc=s.scenes.find(x=>x.id===shot.sceneId)||{};const inherit=k=>shot[k]||sc[k]||'';return {...shot,effectiveLocationId:inherit('locationId'),effectiveLookId:inherit('lookId'),effectiveLightingSetupId:inherit('lightingSetupId'),effectiveCameraSetupId:inherit('cameraSetupId'),effectiveTalentIds:(shot.talentIds?.length?shot.talentIds:sc.talentIds)||[]}}
  function shotReadiness(shot){const e=effectiveShot(shot),missing=[];if(!shot.description?.trim())missing.push('description');if(!(shot.image||shot.referenceAssetIds?.length))missing.push('reference');if(!e.effectiveTalentIds?.length)missing.push('talent');if(!shot.sceneId)missing.push('scene');if(!e.effectiveLocationId)missing.push('location');if(!e.effectiveLookId)missing.push('look');return{ready:missing.length===0,missing,count:missing.length}}
  function projectReadiness(projectId){const [s,p]=ownProject(projectId),sb=DB.getOrCreateStoryboard(p.id),shots=s.shots.filter(x=>x.storyboardId===sb.id),items=shots.map(sh=>({shot:sh,readiness:shotReadiness(sh)})),ready=items.filter(x=>x.readiness.ready).length,issues=items.filter(x=>!x.readiness.ready);return{total:shots.length,ready,issues,percent:shots.length?Math.round(ready/shots.length*100):0,captured:shots.filter(x=>x.captureStatus==='captured').length,retake:shots.filter(x=>x.captureStatus==='retake').length,skipped:shots.filter(x=>x.captureStatus==='skipped').length,remaining:shots.filter(x=>x.captureStatus!=='captured').length}}
  function setProjectContext(projectId,context){const [s,p]=ownProject(projectId);p.lastContext={...context,at:now()};DB.save(s);return p.lastContext}
  function createShotVariation(shotId,size){const s=ensureV12(),src=s.shots.find(x=>x.id===shotId);if(!src)throw new Error('SHOT_NOT_FOUND');let group=src.groupId;if(!group){group=uid('sg');src.groupId=group;s.shotGroups.push({id:group,projectId:s.storyboards.find(x=>x.id===src.storyboardId)?.projectId||'',name:src.description||'Shot Group',createdAt:now()})}const copy=JSON.parse(JSON.stringify(src));copy.id=uid('sh');copy.groupId=group;copy.captureStatus='not_shot';copy.planningStatus='draft';copy.shotSize=size||src.shotSize;copy.position=(src.position||0)+.1;copy.storyOrder=(src.storyOrder||src.position||0)+.1;copy.shootingOrder=(src.shootingOrder||src.position||0)+.1;s.shots.push(copy);normalizeOrders(src.storyboardId,'storyOrder',s);normalizeOrders(src.storyboardId,'shootingOrder',s);DB.save(s);return copy}
  function normalizeOrders(storyboardId,key,s=ensureV12()){s.shots.filter(x=>x.storyboardId===storyboardId).sort((a,b)=>(a[key]||a.position||0)-(b[key]||b.position||0)).forEach((x,i)=>x[key]=i+1);}
  function reorderShotOrder(storyboardId,orderedIds,key='storyOrder'){const s=ensureV12();orderedIds.forEach((id,i)=>{const sh=s.shots.find(x=>x.id===id&&x.storyboardId===storyboardId);if(sh)sh[key]=i+1});DB.save(s);return true}
  function setCaptureStatus(id,status,note=''){const s=ensureV12(),sh=s.shots.find(x=>x.id===id);if(!sh)throw new Error('SHOT_NOT_FOUND');sh.captureStatus=status;if(note)sh.quickNote=note;if(status==='captured')sh.status='Done';else if(status==='retake')sh.status='Review';else if(status==='skipped')sh.status=sh.status==='Done'?'Ready':sh.status;DB.save(s);return sh}
  function nextReadyShot(projectId,currentId,direction=1){const [s,p]=ownProject(projectId),sb=DB.getOrCreateStoryboard(p.id),list=s.shots.filter(x=>x.storyboardId===sb.id).sort((a,b)=>(a.shootingOrder||0)-(b.shootingOrder||0)),idx=Math.max(0,list.findIndex(x=>x.id===currentId));for(let step=1;step<=list.length;step++){const i=idx+step*direction;if(i<0||i>=list.length)break;const sh=list[i];if(sh.captureStatus!=='captured'&&shotReadiness(sh).ready)return sh}return null}
  function shotsByOrder(projectId,key='storyOrder'){const [s,p]=ownProject(projectId),sb=DB.getOrCreateStoryboard(p.id);return s.shots.filter(x=>x.storyboardId===sb.id).sort((a,b)=>(a[key]||a.position||0)-(b[key]||b.position||0))}
  function seedRealityData(){const s=ensureV12(),p=s.photoProjects?.find(x=>x.id==='pp-v10-demo')||s.photoProjects?.[0];if(!p)return;let changed=false;const ensureEntity=(kind,key,name,extra={})=>{const map={location:'projectLocations',look:'projectLooks',prop:'projectProps',lighting:'lightingSetups',camera:'cameraSetups'}[kind];let x=s[map].find(v=>v.projectId===p.id&&v.name===name);if(!x){x={id:key,projectId:p.id,name,createdAt:now(),...extra};s[map].push(x);changed=true}return x};const loc=ensureEntity('location','loc-demo','Studio A',{notes:'Indoor studio · easy power access'});const look=ensureEntity('look','look-demo','Black Editorial Look',{notes:'Black outfit · clean beauty styling'});const light=ensureEntity('lighting','light-demo','Setup A',{notes:'Large soft source camera left · negative fill right'});const cam=ensureEntity('camera','cam-demo','Setup A',{camera:'Sony FX3',lens:'50mm',fps:'24',stabilization:'Handheld'});const sb=s.storyboards.find(x=>x.projectId===p.id),sc=sb?s.scenes.find(x=>x.storyboardId===sb.id):null;if(sc){if(!sc.locationId){sc.locationId=loc.id;sc.lookId=look.id;sc.lightingSetupId=light.id;sc.cameraSetupId=cam.id;changed=true}}if(changed)DB.save(s)}
  seedRealityData();
  Object.assign(DB,{ensureV12,addProjectEntity,updateProjectEntity,entitiesFor,updateSceneV12,effectiveShot,shotReadiness,projectReadiness,setProjectContext,createShotVariation,reorderShotOrder,setCaptureStatus,nextReadyShot,shotsByOrder});
})();
